version: '3.7'

services:
  app:
    image: my-express-app
    ports:
      - '5000:5000'
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PW}
      - MYSQL_DATABASE=${MYSQL_DB}
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD= ${MYSQL_PW}
      - MYSQL_DATABASE= ${MYSQL_DB}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
