version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PW}
      - MYSQL_DATABASE=${MYSQL_DB}
      - TZ=Asia/Seoul
